on: push
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
#        target: ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      env:
        CC: gcc
      with:
#        use-cross: true
        command: build
#        args: --release --target=${{ matrix.target }}
        args: --release
    - shell: bash
      run: |
        ls -la '${{ github.workspace }}'
        ls -la ${{ github.workspace }}/target/
        ls -la ${{ github.workspace }}/target/release/
    - uses: actions/upload-artifact@v1
      with:
        name: release - ${{ matrix.platform }}
        path: ${{ github.workspace }}/target/release/cross-compile-sample
