name: Local-Build

on:
  push:
    branches:
      - leet-*

jobs:
  build:
    name: Building Binaries
    runs-on: self-hosted
#    strategy:
#      matrix:
#        platform: [ubuntu-latest, macos-latest, windows-latest]
#    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
#          - armv7-unknown-linux-gnueabihf
#          - powerpc64-unknown-linux-gnu
#          - aarch64-unknown-linux-gnu
#          - aarch64-unknown-linux-musl
#          - x86_64-pc-windows-gnu
#          - x86_64-pc-windows-msvc
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v2
      - name: Setup Rush tool
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build Binaries
        uses: actions-rs/cargo@v1
        env:
          CC: gcc
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: Debug Paths
        shell: bash
        continue-on-error: true  # WARNING: only for this example, remove it!
        run: |
          ls -la '${{ github.workspace }}'
          ls -la '${{ github.workspace }}/target/'
          ls -la '${{ github.workspace }}/target/${{ matrix.target }}/'
          ls -la '${{ github.workspace }}/target/${{ matrix.target }}/release/'
      - name: Uploads binaries
        uses: actions/upload-artifact@v2
        with:
          name: 'test-${{ matrix.target }}-release'
          path: '${{ github.workspace }}/target/${{ matrix.target }}/release/cross-compile-sample*'
